# Generated by Django 3.2.6 on 2021-09-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0003_auto_20210915_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_validation',
            name='img_h',
        ),
        migrations.RemoveField(
            model_name='image_validation',
            name='img_w',
        ),
    ]
