# Generated by Django 3.2.6 on 2021-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0004_auto_20210915_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_validation',
            name='thumnnail_img_field',
            field=models.ImageField(null=True, upload_to='img_validation'),
        ),
    ]
