# Generated by Django 3.2.6 on 2021-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0006_remove_image_validation_thumnnail_img_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_validation',
            name='img_thumb',
            field=models.ImageField(null=True, upload_to='img_validation_thumb'),
        ),
    ]
