# Generated by Django 3.2.6 on 2021-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0007_image_validation_img_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_validation',
            name='img_field',
            field=models.ImageField(null=True, upload_to='img_validation/'),
        ),
        migrations.AlterField(
            model_name='image_validation',
            name='img_thumb',
            field=models.ImageField(null=True, upload_to='img_validation_thumb/'),
        ),
    ]
