# Generated by Django 3.2.6 on 2021-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0009_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_fields',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
