# Generated by Django 3.2.6 on 2021-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0010_dynamic_fields_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic_fields',
            name='interest',
            field=models.TextField(default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dynamic_fields',
            name='user',
            field=models.CharField(default='[]', max_length=50, null=True),
        ),
    ]
