# Generated by Django 3.2.6 on 2021-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0016_auto_20210917_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_fields',
            name='n_i',
            field=models.JSONField(default=dict, max_length=500, null=True),
        ),
    ]
