# Generated by Django 3.2.6 on 2021-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_us', '0002_auto_20210924_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='msg',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
