# Generated by Django 3.2.6 on 2021-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, null=True, verbose_name='First name')),
                ('l_name', models.CharField(max_length=100, null=True, verbose_name='Last name')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('relationship_status', models.CharField(max_length=100, null=True, verbose_name='Relationship status')),
                ('language_known', models.CharField(max_length=100, null=True, verbose_name='Language Known')),
                ('hobbies', models.CharField(max_length=100, null=True, verbose_name='Hobbies')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Profile picture')),
            ],
        ),
    ]
