# Generated by Django 3.2.6 on 2021-09-09 06:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='TelePhone',
            field=models.IntegerField(blank=True, default=None, verbose_name='TelePhone'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='district',
            field=models.TextField(max_length=200, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='door_num',
            field=models.IntegerField(null=True, verbose_name='Door Number'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='TelePhone'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='town_city',
            field=models.TextField(max_length=200, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='Zip code'),
        ),
    ]
