# Generated by Django 3.2.6 on 2021-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210909_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='confirm_password',
            field=models.CharField(max_length=200, null=True, verbose_name='Confirm Password'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='course_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='institute_address',
            field=models.TextField(max_length=200, null=True, verbose_name='Institute address'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='institute_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Institute Name'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='passed_year',
            field=models.IntegerField(null=True, verbose_name='Passed year'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='password',
            field=models.CharField(max_length=200, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='percentage_gpa',
            field=models.IntegerField(null=True, verbose_name='Percentage/GPA'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='started_year',
            field=models.IntegerField(null=True, verbose_name='Started year'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='uploaded_resume', verbose_name='Upload resume'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='district',
            field=models.CharField(max_length=200, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='town_city',
            field=models.CharField(max_length=200, null=True, verbose_name='Town/City'),
        ),
    ]
