# Generated by Django 3.2.6 on 2021-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_personal_details_percentage_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='door_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Door Number'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='percentage_gpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentage/GPA'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic', verbose_name='Profile picture'),
        ),
    ]
