# Generated by Django 3.2.6 on 2021-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_auto_20210913_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='upload_resume',
            field=models.FileField(blank=True, default=None, upload_to='uploaded_resume', verbose_name='Upload resume'),
        ),
    ]
