# Generated by Django 3.2.6 on 2021-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_personal_details_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='TelePhone',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='telePhone',
            field=models.IntegerField(blank=True, default=None, verbose_name='TelePhone'),
        ),
    ]
