# Generated by Django 3.2.6 on 2021-09-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_auto_20210913_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='mobile',
        ),
    ]
