# Generated by Django 3.2.6 on 2021-09-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_alter_personal_details_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='mobile',
        ),
    ]
