# Generated by Django 3.2.6 on 2021-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_personal_details_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='telePhone',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='TelePhone'),
        ),
    ]
