# Generated by Django 3.2.6 on 2021-09-13 12:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_alter_personal_details_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='relationship_status',
            field=models.CharField(choices=[(1, 'Married'), (2, 'Unmarried')], max_length=100, null=True, verbose_name='Relationship status'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='uploaded_resume', verbose_name='Upload resume'),
        ),
    ]
