# Generated by Django 3.2.6 on 2021-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0028_alter_personal_details_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='relationship_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default=None, max_length=50, null=True, verbose_name='RelationShip status'),
        ),
    ]
