# Generated by Django 3.2.6 on 2021-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0029_auto_20210914_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='percentage_gpa',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Percentage/GPA'),
        ),
    ]
