# Generated by Django 3.2.6 on 2021-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0031_alter_personal_details_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='mobile',
            field=models.CharField(default='+91', max_length=50, null=True, verbose_name='Mobile Number'),
        ),
    ]
